// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEClewMxSZ0dKYpVXBPRJZvvbHEiWdsEI',
    appId: '1:581593628839:web:e4db33092ea309ae7bdb82',
    messagingSenderId: '581593628839',
    projectId: 'hospital-714a1',
    authDomain: 'hospital-714a1.firebaseapp.com',
    storageBucket: 'hospital-714a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYxIZkx8-iTPCWUYFsi9CyyLWHBcL7t3g',
    appId: '1:581593628839:android:2a5668abae2c87b67bdb82',
    messagingSenderId: '581593628839',
    projectId: 'hospital-714a1',
    storageBucket: 'hospital-714a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD0cgGAANnp15ZVi93d1i3qwCh2mk2a7A',
    appId: '1:581593628839:ios:7ba992e1eda5f7937bdb82',
    messagingSenderId: '581593628839',
    projectId: 'hospital-714a1',
    storageBucket: 'hospital-714a1.firebasestorage.app',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD0cgGAANnp15ZVi93d1i3qwCh2mk2a7A',
    appId: '1:581593628839:ios:7ba992e1eda5f7937bdb82',
    messagingSenderId: '581593628839',
    projectId: 'hospital-714a1',
    storageBucket: 'hospital-714a1.firebasestorage.app',
    iosBundleId: 'com.example.hospital',
  );
}
